19-02-02-The-Complete-Elixir-And-Phoenix-Bootcamp/05-Phoenix/discuss/web/router.ex
defmodule Discuss.Router do
  use Discuss.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    # Adding the custom plug to the pipeline
    plug Discuss.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Discuss do
    pipe_through :browser # Use the default browser stack

    # If somebody makes a request to "/topics/new"
    # -> send them to TopicController and run function "new"
    #get "/topics/new", TopicController, :new
    #post "/topics", TopicController, :create
    #get "/topics", TopicController, :index
    get "/", TopicController, :index
    # Adding a route using a wildcard.
    #get "/topics/:id/edit", TopicController, :edit
    #put "/topics/:id", TopicController, :update
    #del "/topics/:id", TopicController, :delete
    # Resources assume a certain REST convention
    # Details: https://hexdocs.pm/phoenix/routing.html#resources
    resources "/topics", TopicController

  end

  scope "/auth", Discuss do
    # pipe_through => for any request for the scope do some specified pre-processing
    pipe_through :browser

    # The request function / module is already defined by the UeberAuth in the auth_controller.ex
    # Using :provider instead of just "github", it will handle all types of providers, f.e. Google etc.
    get "/signout", AuthController, :signout
    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
  end

  # Other scopes may use custom stacks.
  # scope "/api", Discuss do
  #   pipe_through :api
  # end
end

19-02-02-The-Complete-Elixir-And-Phoenix-Bootcamp/05-Phoenix/discuss/web/views/layout_view.ex
defmodule Discuss.LayoutView do
  use Discuss.Web, :view
end

19-02-02-The-Complete-Elixir-And-Phoenix-Bootcamp/05-Phoenix/discuss/web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Discuss!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <!-- Materialize CSS -->
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <script>
  <%= if @conn.assigns.user do %>
    window.userToken = "<%= Phoenix.Token.sign(Discuss.Endpoint, "key", @conn.assigns.user.id)%>"
  <% end %>
    </script>
  </head>

  <body>
  <nav class="light-blue">
    <div class="nav-wrapper container">
      <a href="/" class="brand-logo">
        Discussion
      </a>
      <ul class="right">
        <%= if @conn.assigns[:user] do %>
          <li>
            <%= link "Sign out", to: auth_path(@conn, :signout) %>
          </li>
        <% else %>
          <li>
            <%= link "Sign in with Github", to: auth_path(@conn, :request, "github") %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>

    <div class="container">

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>